#!/usr/bin/env python3
"""
ポケふたNDJSONデータからPostgreSQL INSERTステートメントを生成するスクリプト

使い方:
    # 全件出力
    python tools/generate_manhole_sql.py

    # ID 100以下のみ出力
    python tools/generate_manhole_sql.py --max-id 100

    # ID 50から100まで出力
    python tools/generate_manhole_sql.py --min-id 50 --max-id 100

    # ID 200以上のみ出力
    python tools/generate_manhole_sql.py --min-id 200

機能:
    - GitHubから最新のpokefuta.ndjsonを取得
    - PostgreSQL + PostGIS形式のINSERT文を生成
    - ON CONFLICT DO UPDATE で既存データを更新
    - ポケモン名の配列、位置情報（PostGIS POINT）に対応
    - ID範囲を指定して出力可能
"""

import argparse
import json
import sys
import urllib.request
from datetime import datetime

# GitHubの最新NDJSONファイルURL
NDJSON_URL = "https://raw.githubusercontent.com/nishiokya/pokefuta-tracker/main/apps/web/pokefuta.ndjson"

# Prefecture code mapping (都道府県コードマッピング)
PREFECTURE_CODE_MAP = {
    '北海道': '01', '青森県': '02', '岩手県': '03', '宮城県': '04',
    '秋田県': '05', '山形県': '06', '福島県': '07', '茨城県': '08',
    '栃木県': '09', '群馬県': '10', '埼玉県': '11', '千葉県': '12',
    '東京都': '13', '神奈川県': '14', '新潟県': '15', '富山県': '16',
    '石川県': '17', '福井県': '18', '山梨県': '19', '長野県': '20',
    '岐阜県': '21', '静岡県': '22', '愛知県': '23', '三重県': '24',
    '滋賀県': '25', '京都府': '26', '大阪府': '27', '兵庫県': '28',
    '奈良県': '29', '和歌山県': '30', '鳥取県': '31', '島根県': '32',
    '岡山県': '33', '広島県': '34', '山口県': '35', '徳島県': '36',
    '香川県': '37', '愛媛県': '38', '高知県': '39', '福岡県': '40',
    '佐賀県': '41', '長崎県': '42', '熊本県': '43', '大分県': '44',
    '宮崎県': '45', '鹿児島県': '46', '沖縄県': '47',
}


def escape_sql_string(s):
    """SQL文字列をエスケープ"""
    if s is None:
        return "NULL"
    # シングルクォートをエスケープ
    return "'" + str(s).replace("'", "''") + "'"


def escape_array(arr):
    """PostgreSQL配列形式にエスケープ"""
    if not arr:
        return "ARRAY[]::TEXT[]"

    # 配列の各要素をエスケープ
    escaped_items = [escape_sql_string(item) for item in arr]
    return "ARRAY[" + ", ".join(escaped_items) + "]"


def generate_sql_from_ndjson(ndjson_url=NDJSON_URL, min_id=None, max_id=None):
    """NDJSONからSQL INSERT文を生成

    Args:
        ndjson_url: NDJSONファイルのURL
        min_id: 最小ID（この値以上のIDを出力）
        max_id: 最大ID（この値以下のIDを出力）
    """

    print(f"-- ポケふたマンホールデータ SQL生成スクリプト", file=sys.stderr)
    print(f"-- 生成日時: {datetime.now().isoformat()}", file=sys.stderr)
    print(f"-- データソース: {ndjson_url}", file=sys.stderr)

    if min_id is not None or max_id is not None:
        filter_msg = "-- フィルタ: "
        if min_id is not None and max_id is not None:
            filter_msg += f"ID {min_id} ~ {max_id}"
        elif min_id is not None:
            filter_msg += f"ID {min_id}以上"
        elif max_id is not None:
            filter_msg += f"ID {max_id}以下"
        print(filter_msg, file=sys.stderr)

    print("", file=sys.stderr)

    # GitHubからNDJSONを取得
    try:
        print(f"データを取得中... {ndjson_url}", file=sys.stderr)
        with urllib.request.urlopen(ndjson_url) as response:
            ndjson_content = response.read().decode('utf-8')
    except Exception as e:
        print(f"エラー: データの取得に失敗しました: {e}", file=sys.stderr)
        sys.exit(1)

    # SQL生成
    print("-- ==========================================")
    print("-- ポケふたマンホールデータ INSERT文")
    print(f"-- 生成日時: {datetime.now().isoformat()}")
    print(f"-- データソース: {ndjson_url}")
    print("-- ==========================================")
    print("")
    print("-- テーブルが存在しない場合は作成")
    print("CREATE TABLE IF NOT EXISTS public.manhole (")
    print("  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,")
    print("  title TEXT,")
    print("  prefecture TEXT,")
    print("  prefecture_id INTEGER,")
    print("  prefecture_code VARCHAR(2),")
    print("  municipality TEXT,")
    print("  address TEXT,")
    print("  region TEXT,")
    print("  location GEOGRAPHY,")
    print("  pokemons TEXT[],")
    print("  detail_url TEXT,")
    print("  prefecture_site_url TEXT,")
    print("  is_active BOOLEAN DEFAULT true,")
    print("  last_verified_at TIMESTAMPTZ DEFAULT NOW(),")
    print("  data_source TEXT,")
    print("  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()")
    print(");")
    print("")
    print("-- インデックス作成")
    print("CREATE INDEX IF NOT EXISTS idx_manhole_location_gist ON public.manhole USING GIST(location);")
    print("CREATE INDEX IF NOT EXISTS idx_manhole_prefecture_id ON public.manhole(prefecture_id);")
    print("CREATE INDEX IF NOT EXISTS idx_manhole_prefecture_code ON public.manhole(prefecture_code);")
    print("CREATE INDEX IF NOT EXISTS idx_manhole_address ON public.manhole(address);")
    print("CREATE INDEX IF NOT EXISTS idx_manhole_is_active ON public.manhole(is_active);")
    print("CREATE INDEX IF NOT EXISTS idx_manhole_prefecture_active ON public.manhole(prefecture_id, is_active);")
    print("")

    count = 0
    errors = 0

    for line_num, line in enumerate(ndjson_content.strip().split('\n'), 1):
        if not line.strip():
            continue

        try:
            data = json.loads(line)

            # 必須フィールドのチェック
            if not all(key in data for key in ['id', 'lat', 'lng', 'prefecture']):
                print(f"-- 警告: 行 {line_num} - 必須フィールドが不足しています", file=sys.stderr)
                errors += 1
                continue

            # データ抽出
            manhole_id = int(data['id'])

            # ID範囲フィルタ
            if min_id is not None and manhole_id < min_id:
                continue
            if max_id is not None and manhole_id > max_id:
                continue

            title = data.get('title', '')
            prefecture = data.get('prefecture', '')
            prefecture_code = PREFECTURE_CODE_MAP.get(prefecture, None)
            municipality = data.get('city', None)
            address = data.get('address', None)
            lat = float(data['lat'])
            lng = float(data['lng'])
            pokemons = data.get('pokemons', [])
            detail_url = data.get('detail_url', None)
            prefecture_site_url = data.get('prefecture_site_url', None)

            # PostGIS POINT形式: POINT(経度 緯度)
            location = f"POINT({lng} {lat})"

            # INSERT文生成（ON CONFLICT DO UPDATE）
            sql = f"""INSERT INTO public.manhole (id, title, prefecture, prefecture_code, municipality, address, location, pokemons, detail_url, prefecture_site_url, last_verified_at)
VALUES (
  {manhole_id},
  {escape_sql_string(title)},
  {escape_sql_string(prefecture)},
  {escape_sql_string(prefecture_code)},
  {escape_sql_string(municipality)},
  {escape_sql_string(address)},
  ST_GeogFromText('SRID=4326;{location}'),
  {escape_array(pokemons)},
  {escape_sql_string(detail_url)},
  {escape_sql_string(prefecture_site_url)},
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  prefecture = EXCLUDED.prefecture,
  prefecture_code = EXCLUDED.prefecture_code,
  municipality = EXCLUDED.municipality,
  address = EXCLUDED.address,
  location = EXCLUDED.location,
  pokemons = EXCLUDED.pokemons,
  detail_url = EXCLUDED.detail_url,
  prefecture_site_url = EXCLUDED.prefecture_site_url,
  last_verified_at = NOW();
"""
            print(sql)
            count += 1

        except json.JSONDecodeError as e:
            print(f"-- エラー: 行 {line_num} - JSON解析失敗: {e}", file=sys.stderr)
            errors += 1
        except Exception as e:
            print(f"-- エラー: 行 {line_num} - {e}", file=sys.stderr)
            errors += 1

    # サマリー
    print("", file=sys.stderr)
    print(f"完了: {count}件のマンホールデータを処理しました", file=sys.stderr)
    if errors > 0:
        print(f"警告: {errors}件のエラーがありました", file=sys.stderr)


def main():
    """メイン関数：コマンドライン引数を解析してSQL生成を実行"""
    parser = argparse.ArgumentParser(
        description='ポケふたNDJSONデータからPostgreSQL INSERTステートメントを生成',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
使用例:
  # 全件出力
  python tools/generate_manhole_sql.py > manhole_data.sql

  # ID 100以下のみ出力
  python tools/generate_manhole_sql.py --max-id 100 > manhole_data.sql

  # ID 50から100まで出力
  python tools/generate_manhole_sql.py --min-id 50 --max-id 100 > manhole_data.sql

  # ID 200以上のみ出力（新規追加分のみ）
  python tools/generate_manhole_sql.py --min-id 200 > new_manholes.sql
        """
    )

    parser.add_argument(
        '--min-id',
        type=int,
        metavar='ID',
        help='最小ID（この値以上のIDを出力）'
    )

    parser.add_argument(
        '--max-id',
        type=int,
        metavar='ID',
        help='最大ID（この値以下のIDを出力）'
    )

    parser.add_argument(
        '--url',
        default=NDJSON_URL,
        metavar='URL',
        help=f'NDJSONファイルのURL（デフォルト: {NDJSON_URL}）'
    )

    args = parser.parse_args()

    # バリデーション
    if args.min_id is not None and args.max_id is not None:
        if args.min_id > args.max_id:
            print("エラー: --min-id は --max-id より小さい値を指定してください", file=sys.stderr)
            sys.exit(1)

    # SQL生成実行
    generate_sql_from_ndjson(
        ndjson_url=args.url,
        min_id=args.min_id,
        max_id=args.max_id
    )


if __name__ == "__main__":
    main()
